Data Visualization and understanding of features

In [46]:
import importlib
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import functions
importlib.reload(functions)
import functions

In [19]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\carlo\miniforge3\envs\dtu02452\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\carlo\miniforge3\envs\dtu02452\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [20]:
data = pd.read_excel(r'C:\Users\carlo\OneDrive - Universidade de Lisboa\Documents\GitHub\Hiring-Challenge-E-Commerce-Customer-Segmentation\Online Retail.xlsx')
data.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [21]:
print(data["CustomerID"].isna().sum()) # see how many rows have missing CustomerID values

print((data["Quantity"] < 0).sum()) # see how many rows have negative Quantity values

135080
10624

In [32]:
from functions import data_cleaning

data_cleaned = data_cleaning(data)

In [33]:
# validation of the data cleaning function
print(data_cleaned["CustomerID"].isna().sum() == 0 )
print((data_cleaned["Quantity"] < 0).sum() == 0)

True
True

In [34]:
from functions import calculate_recency, calculate_frequency, calculate_monetary


recency = calculate_recency(data)
frequency = calculate_frequency(data)
monetary = calculate_monetary(data)

In [35]:
print(recency.head())
print(frequency.head()) 
print(monetary.head())

   CustomerID  Recency
0     12346.0      325
1     12347.0        1
2     12348.0       74
3     12349.0       18
4     12350.0      309
   CustomerID  Frequency
0     12346.0          2
1     12347.0          7
2     12348.0          4
3     12349.0          1
4     12350.0          1
   CustomerID  Monetary
0     12346.0      0.00
1     12347.0   4310.00
2     12348.0   1797.24
3     12349.0   1757.55
4     12350.0    334.40

In [36]:
rfm_data = recency.merge(frequency, on="CustomerID")
rfm_data = rfm_data.merge(monetary, on="CustomerID")

In [37]:
print(rfm_data.head())

   CustomerID  Recency  Frequency  Monetary
0     12346.0      325          2      0.00
1     12347.0        1          7   4310.00
2     12348.0       74          4   1797.24
3     12349.0       18          1   1757.55
4     12350.0      309          1    334.40

In [44]:
print(rfm_data[rfm_data["Monetary"] == 0])

      CustomerID  Recency  Frequency  Monetary
0        12346.0      325          2       0.0
692      13256.0       13          1       0.0
775      13364.0       66          2       0.0
1642     14557.0       63          2       0.0
1809     14792.0       63          2       0.0
3245     16742.0       46          2       0.0
3349     16878.0       24          2       0.0
4358     18268.0      133          2       0.0

In [48]:
from functions import clean_rfm_data

rfm_data = clean_rfm_data(rfm_data)
rfm_data.head()

   CustomerID  Recency  Frequency  Monetary
1     12347.0        1          7   4310.00
2     12348.0       74          4   1797.24
3     12349.0       18          1   1757.55
4     12350.0      309          1    334.40
5     12352.0       35         11   1545.41